version: "4"

services:
  m_project:
    container_name: paste_proj
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      app-network:
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: postgresql://testing_d014_user:fM6QP5iJd8iYZC4ZV82HWyGOyTNoztZG@dpg-ctlag0bqf0us73879oag-a.oregon-postgres.render.com/testing_d014
      SPRING_DATASOURCE_USERNAME: testing_d014_user
      SPRING_DATASOURCE_PASSWORD: fM6QP5iJd8iYZC4ZV82HWyGOyTNoztZG

networks:
  app-network:
    driver: bridge